version: '3.8'

services:
  webapp:
    build:
      context: .
      dockerfile: ./dev/Dockerfile-dev
    container_name: webapp_dev_cont
    environment:
      - DJANGO_SUPERUSER_PASSWORD='adminpw'
      - DJANGO_SUPERUSER_EMAIL='cours.lyco@gmail.com'
      - DJANGO_SUPERUSER_USERNAME='admin'
    command:
      - /bin/bash
      - -c
      - |
        python /usr/src/app/myproject/manage.py collectstatic --noinput
        python /usr/src/app/myproject/manage.py makemigrations
        python /usr/src/app/myproject/manage.py migrate
        python /usr/src/app/myproject/manage.py makemigrations utils_appconfig
        python /usr/src/app/myproject/manage.py migrate utils_appconfig
        source /usr/src/app/create_superuser_dev.sh
        python /usr/src/app/myproject/manage.py runserver 0.0.0.0:8000
    volumes:
      - static_volume:/usr/src/app/myproject/myproject/static
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db

  db:
    image: postgres:12.0-alpine
    container_name: db_dev_cont
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_db
      - POSTGRES_HOST_AUTH_METHOD=trust

volumes:
  static_volume:
  postgres_data:
