version: '3.8'

services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile-nginx
    container_name: nginx_prod_cont
    volumes:
      - static_volume:/home/app/web/myproject/myproject/static
      - media_volume:/home/app/web/mediafiles
    ports:
      - 1337:80
    depends_on:
      - webapp

  webapp:
    build:
      context: .
      dockerfile: ./prod/Dockerfile-prod
    container_name: webbapp_prod_cont
    command: sh -c "cd ./myproject && gunicorn myproject.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - static_volume:/home/app/web/myproject/myproject/static
      - media_volume:/home/app/web/mediafiles
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db

  db:
    image: postgres:12.0-alpine
    container_name: db_prod_cont
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db

volumes:
  postgres_data:
  static_volume:
  media_volume:
