FROM python:3.8-alpine

ENV LANG C.UTF-8
ENV LC_ALL C.UTF-8

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Install curl
RUN apk --no-cache add curl



# Install required package
RUN apk update && \
    apk add --no-cache --virtual .build-deps \
    ca-certificates mariadb-dev  \
    gcc postgresql-dev linux-headers  \
    libffi-dev openssl-dev musl-dev jpeg-dev zlib-dev \
    git bash \
    build-base \
    libffi-dev \
    libjpeg-turbo-dev \
    zlib-dev  && \
    pip install mysqlclient 
    
WORKDIR /app

COPY ./requirements.txt ./

# Install requirements.txt
#RUN pip install --no-cache-dir -r  ./requirements.txt
RUN pip install  --use-pep517 -r  ./requirements.txt

COPY .  .


